const { alpha, mix } = require("./resolve");

// Resolved variant -> workbench `colors`.
module.exports = function uiColors(t) {
  const { hues: h, ink, accent, opts } = t;
  const side = opts.contrastSidebar ? t.bg0 : t.bg1;
  const chrome = t.bg0;
  const line = opts.bordered ? t.surface0 : null;
  const border = (fallback) => line || fallback;
  const sel = alpha(accent, t.dark ? 0.28 : 0.22);
  const hover = alpha(t.surface0, 0.7);

  return {
    // base
    focusBorder: alpha(accent, 0.6),
    foreground: t.fg,
    descriptionForeground: t.muted,
    disabledForeground: t.muted,
    errorForeground: h.red,
    "icon.foreground": t.subtle,
    "selection.background": sel,
    "widget.shadow": alpha("#000000", t.dark ? 0.45 : 0.15),
    "widget.border": border(t.surface0),
    "sash.hoverBorder": accent,
    "textLink.foreground": t.accentText,
    "textLink.activeForeground": t.accentText,
    "textCodeBlock.background": t.bg1,
    "textBlockQuote.background": t.bg1,
    "textBlockQuote.border": accent,
    "textPreformat.foreground": t.roles.string,
    "textSeparator.foreground": t.surface1,

    // window chrome
    "titleBar.activeBackground": chrome,
    "titleBar.activeForeground": t.subtle,
    "titleBar.inactiveBackground": chrome,
    "titleBar.inactiveForeground": t.muted,
    "titleBar.border": border(chrome),
    "menu.background": t.bg1,
    "menu.foreground": t.fg,
    "menu.selectionBackground": t.surface0,
    "menu.separatorBackground": t.surface0,
    "menu.border": t.surface0,
    "menubar.selectionBackground": t.surface0,
    "commandCenter.background": t.bg1,
    "commandCenter.activeBackground": t.surface0,
    "commandCenter.foreground": t.subtle,
    "commandCenter.border": t.surface0,

    // activity bar
    "activityBar.background": chrome,
    "activityBar.foreground": accent,
    "activityBar.inactiveForeground": t.muted,
    "activityBar.activeBorder": accent,
    "activityBar.activeBackground": alpha(accent, 0.08),
    "activityBar.border": border(chrome),
    "activityBarBadge.background": accent,
    "activityBarBadge.foreground": t.onAccent,
    "activityBarTop.foreground": accent,
    "activityBarTop.inactiveForeground": t.muted,
    "activityBarTop.activeBorder": accent,

    // side bar
    "sideBar.background": side,
    "sideBar.foreground": t.subtle,
    "sideBar.border": border(side),
    "sideBarTitle.foreground": t.subtle,
    "sideBarSectionHeader.background": side,
    "sideBarSectionHeader.foreground": t.fg,
    "sideBarSectionHeader.border": border(side),
    "list.activeSelectionBackground": alpha(accent, 0.2),
    "list.activeSelectionForeground": t.fg,
    "list.activeSelectionIconForeground": t.fg,
    "list.inactiveSelectionBackground": t.surface0,
    "list.inactiveSelectionForeground": t.fg,
    "list.hoverBackground": hover,
    "list.hoverForeground": t.fg,
    "list.focusBackground": alpha(accent, 0.15),
    "list.focusOutline": alpha(accent, 0.5),
    "list.highlightForeground": t.accentText,
    "list.focusHighlightForeground": t.accentText,
    "list.dropBackground": alpha(accent, 0.15),
    "list.errorForeground": ink.red,
    "list.warningForeground": ink.yellow,
    "tree.indentGuidesStroke": t.surface1,
    "tree.inactiveIndentGuidesStroke": t.surface0,

    // editor
    "editor.background": t.bg2,
    "editor.foreground": t.fg,
    "editorLineNumber.foreground": t.surface2,
    "editorLineNumber.activeForeground": t.subtle,
    "editorCursor.foreground": accent,
    "editor.selectionBackground": sel,
    "editor.inactiveSelectionBackground": alpha(accent, 0.12),
    "editor.selectionHighlightBackground": alpha(accent, 0.14),
    "editor.wordHighlightBackground": alpha(t.subtle, 0.12),
    "editor.wordHighlightStrongBackground": alpha(accent, 0.18),
    "editor.findMatchBackground": alpha(h.peach, 0.4),
    "editor.findMatchHighlightBackground": alpha(h.peach, 0.2),
    "editor.findRangeHighlightBackground": alpha(t.surface0, 0.5),
    "editor.lineHighlightBackground": alpha(t.surface0, t.dark ? 0.45 : 0.5),
    "editor.lineHighlightBorder": "#00000000",
    "editor.rangeHighlightBackground": alpha(t.surface0, 0.5),
    "editor.hoverHighlightBackground": alpha(accent, 0.12),
    "editorLink.activeForeground": t.accentText,
    "editorWhitespace.foreground": alpha(t.surface2, 0.6),
    "editorIndentGuide.background1": t.surface0,
    "editorIndentGuide.activeBackground1": t.surface2,
    "editorRuler.foreground": t.surface0,
    "editorCodeLens.foreground": t.muted,
    "editorBracketMatch.background": alpha(accent, 0.15),
    "editorBracketMatch.border": alpha(accent, 0.6),
    "editorBracketHighlight.foreground1": h.yellow,
    "editorBracketHighlight.foreground2": h.mauve,
    "editorBracketHighlight.foreground3": h.sky,
    "editorBracketHighlight.foreground4": h.peach,
    "editorBracketHighlight.foreground5": h.green,
    "editorBracketHighlight.foreground6": h.rose,
    "editorBracketHighlight.unexpectedBracket.foreground": h.red,
    "editorError.foreground": h.red,
    "editorWarning.foreground": h.yellow,
    "editorInfo.foreground": h.blue,
    "editorHint.foreground": h.teal,
    "editorInlayHint.background": alpha(t.surface0, 0.6),
    "editorInlayHint.foreground": t.muted,
    "editorGhostText.foreground": alpha(t.muted, 0.8),
    "editorUnnecessaryCode.opacity": "#000000a0",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.errorForeground": h.red,
    "editorOverviewRuler.warningForeground": h.yellow,
    "editorOverviewRuler.infoForeground": h.blue,
    "editorOverviewRuler.modifiedForeground": h.blue,
    "editorOverviewRuler.addedForeground": h.green,
    "editorOverviewRuler.deletedForeground": h.red,
    "editorGutter.modifiedBackground": h.blue,
    "editorGutter.addedBackground": h.green,
    "editorGutter.deletedBackground": h.red,
    "editorStickyScroll.background": t.bg2,
    "editorStickyScroll.shadow": alpha("#000000", t.dark ? 0.4 : 0.1),
    "editorStickyScrollHover.background": t.surface0,

    // editor widgets
    "editorWidget.background": t.bg1,
    "editorWidget.foreground": t.fg,
    "editorWidget.border": t.surface0,
    "editorSuggestWidget.background": t.bg1,
    "editorSuggestWidget.border": t.surface0,
    "editorSuggestWidget.foreground": t.subtle,
    "editorSuggestWidget.selectedBackground": t.surface0,
    "editorSuggestWidget.highlightForeground": t.accentText,
    "editorHoverWidget.background": t.bg1,
    "editorHoverWidget.border": t.surface0,
    "peekView.border": accent,
    "peekViewEditor.background": t.bg1,
    "peekViewResult.background": t.bg0,
    "peekViewTitle.background": t.bg0,
    "peekViewEditor.matchHighlightBackground": alpha(h.peach, 0.3),
    "peekViewResult.matchHighlightBackground": alpha(h.peach, 0.3),
    "peekViewResult.selectionBackground": t.surface0,
    "minimap.background": t.bg2,
    "minimap.selectionHighlight": alpha(accent, 0.5),
    "minimapSlider.background": alpha(t.surface1, 0.3),
    "minimapSlider.hoverBackground": alpha(t.surface1, 0.5),
    "minimapSlider.activeBackground": alpha(t.surface1, 0.7),
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": alpha(t.surface1, 0.45),
    "scrollbarSlider.hoverBackground": alpha(t.surface1, 0.7),
    "scrollbarSlider.activeBackground": alpha(t.surface2, 0.8),

    // tabs + breadcrumbs
    "editorGroupHeader.tabsBackground": t.bg1,
    "editorGroupHeader.noTabsBackground": t.bg2,
    "editorGroupHeader.tabsBorder": border(t.bg1),
    "editorGroup.border": t.surface0,
    "editorGroup.dropBackground": alpha(accent, 0.12),
    "tab.activeBackground": t.bg2,
    "tab.activeForeground": t.fg,
    "tab.activeBorderTop": accent,
    "tab.activeBorder": t.bg2,
    "tab.inactiveBackground": t.bg1,
    "tab.inactiveForeground": t.muted,
    "tab.hoverBackground": t.bg2,
    "tab.border": border(t.bg1),
    "tab.unfocusedActiveForeground": t.subtle,
    "tab.unfocusedActiveBorderTop": alpha(accent, 0.4),
    "tab.activeModifiedBorder": h.peach,
    "tab.inactiveModifiedBorder": alpha(h.peach, 0.5),
    "breadcrumb.foreground": t.muted,
    "breadcrumb.focusForeground": t.fg,
    "breadcrumb.activeSelectionForeground": t.accentText,
    "breadcrumb.background": t.bg2,
    "breadcrumbPicker.background": t.bg1,

    // panel + terminal
    "panel.background": side,
    "panel.border": border(t.surface0),
    "panelTitle.activeForeground": t.fg,
    "panelTitle.activeBorder": accent,
    "panelTitle.inactiveForeground": t.muted,
    "panelSection.border": t.surface0,
    "terminal.background": side,
    "terminal.foreground": t.fg,
    "terminalCursor.foreground": accent,
    "terminal.selectionBackground": sel,
    "terminal.ansiBlack": t.dark ? t.surface1 : t.subtle,
    "terminal.ansiBrightBlack": t.dark ? t.surface2 : t.muted,
    "terminal.ansiWhite": t.dark ? t.subtle : t.surface2,
    "terminal.ansiBrightWhite": t.dark ? t.fg : t.surface1,
    "terminal.ansiRed": ink.red,
    "terminal.ansiBrightRed": mix(ink.red, t.fg, 0.2),
    "terminal.ansiGreen": ink.green,
    "terminal.ansiBrightGreen": mix(ink.green, t.fg, 0.2),
    "terminal.ansiYellow": ink.yellow,
    "terminal.ansiBrightYellow": mix(ink.yellow, t.fg, 0.2),
    "terminal.ansiBlue": ink.blue,
    "terminal.ansiBrightBlue": mix(ink.blue, t.fg, 0.2),
    "terminal.ansiMagenta": ink.mauve,
    "terminal.ansiBrightMagenta": mix(ink.mauve, t.fg, 0.2),
    "terminal.ansiCyan": ink.teal,
    "terminal.ansiBrightCyan": mix(ink.teal, t.fg, 0.2),

    // status bar
    "statusBar.background": chrome,
    "statusBar.foreground": t.subtle,
    "statusBar.border": border(chrome),
    "statusBar.noFolderBackground": chrome,
    "statusBar.debuggingBackground": h.peach,
    "statusBar.debuggingForeground": t.dark ? t.bg0 : "#ffffff",
    "statusBarItem.hoverBackground": t.surface0,
    "statusBarItem.remoteBackground": accent,
    "statusBarItem.remoteForeground": t.onAccent,
    "statusBarItem.prominentBackground": t.surface0,
    "statusBarItem.errorForeground": ink.red,
    "statusBarItem.warningForeground": ink.yellow,

    // inputs + buttons
    "input.background": t.surface0,
    "input.foreground": t.fg,
    "input.border": border("#00000000"),
    "input.placeholderForeground": t.muted,
    "inputOption.activeBackground": alpha(accent, 0.25),
    "inputOption.activeBorder": accent,
    "inputValidation.errorBackground": t.bg1,
    "inputValidation.errorBorder": h.red,
    "inputValidation.warningBackground": t.bg1,
    "inputValidation.warningBorder": h.yellow,
    "inputValidation.infoBackground": t.bg1,
    "inputValidation.infoBorder": h.blue,
    "dropdown.background": t.surface0,
    "dropdown.listBackground": t.bg1,
    "dropdown.border": border("#00000000"),
    "dropdown.foreground": t.fg,
    "checkbox.background": t.surface0,
    "checkbox.border": t.surface1,
    "checkbox.foreground": accent,
    "button.background": accent,
    "button.foreground": t.onAccent,
    "button.hoverBackground": mix(accent, t.fg, 0.15),
    "button.secondaryBackground": t.surface0,
    "button.secondaryForeground": t.fg,
    "button.secondaryHoverBackground": t.surface1,
    "badge.background": t.surface1,
    "badge.foreground": t.fg,
    "progressBar.background": accent,
    "keybindingLabel.background": t.surface0,
    "keybindingLabel.foreground": t.fg,
    "keybindingLabel.border": t.surface1,
    "keybindingLabel.bottomBorder": t.surface1,

    // quick input / notifications
    "quickInput.background": t.bg1,
    "quickInput.foreground": t.fg,
    "quickInputList.focusBackground": alpha(accent, 0.2),
    "quickInputTitle.background": t.bg0,
    "pickerGroup.foreground": t.accentText,
    "pickerGroup.border": t.surface0,
    "notifications.background": t.bg1,
    "notifications.foreground": t.fg,
    "notifications.border": t.surface0,
    "notificationCenterHeader.background": t.bg0,
    "notificationsErrorIcon.foreground": h.red,
    "notificationsWarningIcon.foreground": h.yellow,
    "notificationsInfoIcon.foreground": h.blue,
    "notificationLink.foreground": t.accentText,

    // git + diff
    "gitDecoration.addedResourceForeground": ink.green,
    "gitDecoration.modifiedResourceForeground": ink.yellow,
    "gitDecoration.deletedResourceForeground": ink.red,
    "gitDecoration.untrackedResourceForeground": ink.teal,
    "gitDecoration.ignoredResourceForeground": t.muted,
    "gitDecoration.conflictingResourceForeground": ink.peach,
    "gitDecoration.renamedResourceForeground": ink.sky,
    "gitDecoration.submoduleResourceForeground": ink.lavender,
    "diffEditor.insertedTextBackground": alpha(h.green, 0.15),
    "diffEditor.removedTextBackground": alpha(h.red, 0.15),
    "diffEditor.insertedLineBackground": alpha(h.green, 0.08),
    "diffEditor.removedLineBackground": alpha(h.red, 0.08),
    "diffEditor.diagonalFill": t.surface0,
    "merge.currentHeaderBackground": alpha(h.green, 0.4),
    "merge.currentContentBackground": alpha(h.green, 0.15),
    "merge.incomingHeaderBackground": alpha(h.blue, 0.4),
    "merge.incomingContentBackground": alpha(h.blue, 0.15),

    // debug + testing
    "debugToolBar.background": t.bg1,
    "debugIcon.startForeground": h.green,
    "debugIcon.stopForeground": h.red,
    "debugIcon.pauseForeground": h.yellow,
    "debugIcon.continueForeground": h.green,
    "debugIcon.restartForeground": h.teal,
    "debugIcon.stepOverForeground": h.blue,
    "debugIcon.stepIntoForeground": h.blue,
    "debugIcon.stepOutForeground": h.blue,
    "debugIcon.breakpointForeground": h.red,
    "editor.stackFrameHighlightBackground": alpha(h.yellow, 0.15),
    "editor.focusedStackFrameHighlightBackground": alpha(h.green, 0.15),
    "testing.iconPassed": h.green,
    "testing.iconFailed": h.red,
    "testing.iconQueued": h.yellow,
    "testing.iconSkipped": t.muted,

    // misc
    "settings.headerForeground": t.fg,
    "settings.modifiedItemIndicator": accent,
    "welcomePage.tileBackground": t.bg1,
    "walkThrough.embeddedEditorBackground": t.bg1,
    "extensionButton.prominentBackground": accent,
    "extensionButton.prominentForeground": t.onAccent,
    "extensionBadge.remoteBackground": accent,
    "extensionBadge.remoteForeground": t.onAccent,
    "charts.foreground": t.fg,
    "charts.red": h.red,
    "charts.blue": h.blue,
    "charts.yellow": h.yellow,
    "charts.orange": h.peach,
    "charts.green": h.green,
    "charts.purple": h.mauve,
    "symbolIcon.classForeground": h.yellow,
    "symbolIcon.functionForeground": h.blue,
    "symbolIcon.methodForeground": h.blue,
    "symbolIcon.variableForeground": t.fg,
    "symbolIcon.fieldForeground": h.lavender,
    "symbolIcon.propertyForeground": h.lavender,
    "symbolIcon.interfaceForeground": h.yellow,
    "symbolIcon.keywordForeground": h.mauve,
    "symbolIcon.constantForeground": h.peach,
    "symbolIcon.enumeratorForeground": h.yellow,
    "symbolIcon.moduleForeground": h.teal,
  };
};
